# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firstios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'NMSSH'
  # Pods for firstios

  target 'firstiosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'firstiosUITests' do
    # Pods for testing
  end

end
